### ISSUE TITLE
`!Send` support

### ISSUE THREAD

**Issue by mkroening** [WaffleLapkin/takecell#2]
This is more of a FYI than an issue. I just wanted to share with you that I built a similar crate, [take-static], since I needed to put `!Send` types in statics with `TakeCell`s. To make that sound, my crate is only usable for statics, `TakeStatic`s cannot be constructed at run-time.

[take-static]: https://crates.io/crates/take-static

I had previously also built [exclusive_cell], as I was not aware of this project.  It faced the same limitation, though. It's redundant with takecell and take-static now, and I'll refer to takecell and take-static in the future.

[exclusive_cell]: https://crates.io/crates/exclusive_cell

That's all, thanks for your work! :)

**Comment by WaffleLapkin** [comment]
Interesting, thanks for the FYI!
